### ISSUE TITLE
Incorrect semistatic 2 identification

### ISSUE THREAD

**Issue by DerfJagged** [Swizzy/PS3DumpChecker#13]
Had a user with a CECH-H with min firmware 1.97, but it was expecting the value for a CECH-E/CECH-G with min firmware 1.90 (and marking it a bad dump) as according to this page:

http://www.psdevwiki.com/ps3/Talk:Flash:Individual_System_Data_-_cISD#cISD1_0x44

Image of users' dump:
http://i.imgur.com/dQKg0Dr.png

What it should have been expecting:
http://i.imgur.com/KS64WdA.png (which is the actual data in the dump)

**Comment by Swizzy** [comment]
The checker already have this information in the cfg: https://github.com/Swizzy/PS3DumpChecker/blob/master/Latest%20Compiled%20Version/default.cfg#L284 however, if the bytes are not in the expected order, it'll fail it, and that appears to be the case for this dump as all other checks are matching just not this one and not ROS# either (are you even using the latest cfg/hashlist?)

**Comment by DerfJagged** [comment]
Do you think it's due to the actual data field reading as "56 00" instead of "00 56"? Is there something that would cause this? 

You're correct in that it failed ROS0/ROS1, but as far as I know, that's a normal thing and I've always seen people say it's okay if those hash checks fail. He is using the latest build (490) shown in the title bar of the first screenshot. Sequential dumps come up exactly the same, with a matching hash. Any advice if this isn't a program issue? 

Thanks for replying :)

**Comment by LordYusei** [comment]
The only times I've had this error myself was when it was indeed a bad dump. After reseating the e3 Clip and securing it better, I got perfect dumps minus the ROS0 Hash, and successfully downgraded the console. One thing I'll suggest is clean the legs of the nor chip with a cleaner of sorts (I use nail varnish remover), and reapply the nor clip. As even though you can't see anything there there could be something causing the bad dumps.

**Comment by Swizzy** [comment]
It's important that ROS# hash match, if it doesn't it's either because the dump is bad, or because it's a unknown version, a way to make sure it always match is to do a recovery 2 times with the same version that the console is currently on, this ensures both ROS0 and ROS1 have the same version... as long as the hashlist has been updated with support for the version of OFW on the console, it should pass... otherwise you should wait for it to be updated... (ROS# covers the majority of your NOR dump, which means that it's the most likely place for an error to occur)

**Comment by littlebalup** [comment]
About the cISD data "00 56 00 56 00 86", As said by swizzzy, it as been added long time ago : https://github.com/Swizzy/PS3DumpChecker/commit/315377ed983e02ea8862c6e9c47d0dc761660003

It shows "56 00 56 00 86 00" because your dump is byte swapped (E3 flasher dump). PS3dumpchecker shows the raw data but don't care, it recognize it.

So, please, update your CFG (right top corner button). Update your hashlist to (probably bad ROS because your hashlist is outdated). Then check your dump again.

**Comment by DerfJagged** [comment]
I see, thank you all for your help!
