### ISSUE TITLE
Doesn't work on windows 7 and 8

### ISSUE THREAD

**Issue by dangreen** [Swizzy/PS3DumpChecker#6]
Doesn't work on windows 7 and 8
Visual Studio throws `System.TypeInitializationException`

**Comment by Swizzy** [comment]
Can you give me more details as to where this exception is thrown?

Are you using 32 or 64-bit windows?

It's been tested by me on windows 8.1 (64-bit) and by littlebalup on windows 7...

**Comment by dangreen** [comment]
@Swizzy 64-bit windows, Parallels Desktop

**Comment by Swizzy** [comment]
That'd be your problem then, Parallels Desktop... it messes up paths...

https://github.com/Swizzy/PS3DumpChecker/blob/master/src/PS3DumpChecker/Program.cs#L12 <--- this is the faulting line, there are 3 ways you can solve this;

1. Switch to something that doesn't f*ck with the paths
2. Run it in a real windows environment (basically the same as 1 really)
3. Change how the functionality for the icon works so that it doesn't ask windows to find the associated file but rather use a embedded one... i haven't done this because i'm a big fan of minimizing unnecessary data... (having the icon embedded in 2 places is to me stupid when it can be done with just having it embedded for windows display and being able to extract it from there)

Essentially, i'd contact Parallels Desktop developers and tell them to fix the issue...

**Comment by dangreen** [comment]
@Swizzy what if i remove `AppIcon`?

**Comment by Swizzy** [comment]
You can remove it, but then you also have to remove all the references to it... and it'll cause it to not show the icon in the forms...

**Comment by dangreen** [comment]
@Swizzy ok, thank you

**Comment by Crldk** [comment]
How do i run it in a real Windows environment?
